### ISSUE TITLE
Potential issue in wall thickness of v2 top case

### ISSUE THREAD

**Issue by arrowtype** [subottimale/alphalpha_plus#1]
Hey, I'm a big fan of this project and the designs in it. I am considering ordering the top shell case from the v2 files, but when JLCpcb checked it, they emailed me with this message:

> 1/ As shown below, the wall thickness of the indicated red area is very thin. Proceed the printing as it is will meet potential risks of parts missing, deformation, cracking and damage. It is almost certain that the indicated area will turn out broken.
> 
> We would recommend increasing the wall thickness to be above 1.0mm, 2.0mm would be much better.
> 
> 2/ Printing such parts with geometry structure will meet high risks of deformation and warping.
> 
> Could we kindly check with you if you prefer to modify your file or proceed with risks accepted?
> 
> ﻿![image](https://github.com/subottimale/alphalpha_plus/assets/45946693/68f77928-5e03-4e98-8b44-3d619b04ad48)

I haven't yet personally checked the measurements in CAD software, but I assume they are accurate in reporting the concern. If I do modify the design, I'd be happy to make a pull request here, but I am currently leaning towards making the sandwich-style case instead. Still, I thought it might be helpful to share this issue here.

Thanks for making and sharing the project!

**Comment by subottimale** [comment]
The callout is appreciated. Those highlighted areas of the case are thin, but it's been tested three times in PLA and showed no issues - twice by a professional shop, once on a consumer grade printer.

The original aim was for MJF or SLS, but FDM prints have proven out quite well.
